/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebd2proyecto;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tomas
 */
public class GRAFICAR extends javax.swing.JFrame {

    GraficarTable modelo;
    VolumenTable modelo2;
    ReportesDB rep;
    ArrayList<Reportes> lista;
    DB_CONECTION conexion;
    
    /**
     * Creates new form GRAFICAR
     */
    public GRAFICAR() {
        initComponents();
        conexion=new DB_CONECTION();
        rep= new ReportesDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mensual2016_2019 = new javax.swing.JButton();
        transacciones = new javax.swing.JButton();
        mensual2016 = new javax.swing.JButton();
        mensual2017 = new javax.swing.JButton();
        mensual2018 = new javax.swing.JButton();
        mensual2019 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mensual2016_2019.setText("GRAFICA MENSUAL 2016-2019");
        mensual2016_2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensual2016_2019ActionPerformed(evt);
            }
        });

        transacciones.setText("VOLUMEN TRANSACCIONES");
        transacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaccionesActionPerformed(evt);
            }
        });

        mensual2016.setText("GRAFICA MENSUAL 2016");
        mensual2016.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensual2016ActionPerformed(evt);
            }
        });

        mensual2017.setText("GRAFICA MENSUAL 2017");
        mensual2017.setActionCommand("");
        mensual2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensual2017ActionPerformed(evt);
            }
        });

        mensual2018.setText("GRAFICA MENSUAL 2018");
        mensual2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensual2018ActionPerformed(evt);
            }
        });

        mensual2019.setText("GRAFICA MENSUAL 2019");
        mensual2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensual2019ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mensual2018, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensual2016, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensual2017, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transacciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensual2016_2019, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensual2019, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensual2016, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensual2017, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensual2018, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensual2019, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensual2016_2019, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mensual2016_2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensual2016_2019ActionPerformed
        // TODO add your handling code here:
        Image preview = Toolkit.getDefaultToolkit().getImage("img/2016_2019.png");
        ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        //Icon icon = new ImageIcon("/src/img/2016Mensual.png");
       
        
        lista=rep.getReporteMensual1619();
        
        GraficarTable modelo= new GraficarTable(lista);
        jTable1.setModel(modelo);
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_mensual2016_2019ActionPerformed

    private void transaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaccionesActionPerformed
        // TODO add your handling code here:
        
         Image preview = Toolkit.getDefaultToolkit().getImage("img/VolumenMensual.png");
         ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        //Icon icon = new ImageIcon("/src/img/2016Mensual.png");
       
        
        lista=rep.getReporteVolumen();
        
        VolumenTable modelo2= new VolumenTable(lista);
        jTable1.setModel(modelo2);
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_transaccionesActionPerformed

    private void mensual2016ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensual2016ActionPerformed
        // TODO add your handling code here:
        
         Image preview = Toolkit.getDefaultToolkit().getImage("img/2016Mensual.png");
         ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        //Icon icon = new ImageIcon("/src/img/2016Mensual.png");
       
        
        lista=rep.getReporteMensual2016();
        
        GraficarTable modelo= new GraficarTable(lista);
        jTable1.setModel(modelo);
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_mensual2016ActionPerformed

    private void mensual2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensual2017ActionPerformed
        // TODO add your handling code here:
         Image preview = Toolkit.getDefaultToolkit().getImage("img/2017Mensual.png");
         ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        //Icon icon = new ImageIcon("/src/img/2016Mensual.png");
       
        
        lista=rep.getReporteMensual2017();
        
        GraficarTable modelo= new GraficarTable(lista);
        jTable1.setModel(modelo);
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_mensual2017ActionPerformed

    private void mensual2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensual2018ActionPerformed
        // TODO add your handling code here:
         Image preview = Toolkit.getDefaultToolkit().getImage("img/2018Mensual.png");
         ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        //Icon icon = new ImageIcon("/src/img/2016Mensual.png");
       
        
        lista=rep.getReporteMensual2018();
        
        GraficarTable modelo= new GraficarTable(lista);
        jTable1.setModel(modelo);
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_mensual2018ActionPerformed

    private void mensual2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensual2019ActionPerformed
        // TODO add your handling code here:
         Image preview = Toolkit.getDefaultToolkit().getImage("img/2019Mensual.png");
         ImageIcon icon = new ImageIcon(preview.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        //Icon icon = new ImageIcon("/src/img/2016Mensual.png");
       
        
        lista=rep.getReporteMensual2019();
        
        GraficarTable modelo= new GraficarTable(lista);
        jTable1.setModel(modelo);
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_mensual2019ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GRAFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GRAFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GRAFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRAFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GRAFICAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mensual2016;
    private javax.swing.JButton mensual2016_2019;
    private javax.swing.JButton mensual2017;
    private javax.swing.JButton mensual2018;
    private javax.swing.JButton mensual2019;
    private javax.swing.JButton transacciones;
    // End of variables declaration//GEN-END:variables
}
